version: "3.8"
services:
  citynet-fe-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: citynet-fe-dev
    ports:
      - "5173:5173"       
    volumes:
      - .:/app           
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0